name: Build and Push Docker image

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Chequear el cÃ³digo del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> $GITHUB_ENV
          echo "PORT=${{ secrets.PORT }}" >> $GITHUB_ENV

      # 2. Loguearse en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Construir y etiquetar la imagen de Docker
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/micro-blockchain:test .
          docker tag ${{ secrets.DOCKER_USERNAME }}/micro-blockchain:test ${{ secrets.DOCKER_USERNAME }}/micro-blockchain:${{ github.sha }}

      # 4. Subir la imagen a Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/micro-blockchain:test
          docker push ${{ secrets.DOCKER_USERNAME }}/micro-blockchain:${{ github.sha }}

      # 2. Crear el archivo .env con los secrets de GitHub para micro-blockchain
      # - name: Create .env file for micro-blockchain
      #   run: |
      #     cat << EOF >> .env
      #     NODE_ENV=
      #     EOF
